name: Tag and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install

      - name: Update version
        run: echo '${{ github.event.inputs.version }}' > src/version.txt

      - name: Build extension
        run: node ./scripts/build.js all ver

      - name: Release
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          hub release create -a ./build/dist/FastForward_firefox* -a ./build/dist/FastForward_chromium* -m "Release ${{ github.event.inputs.version }}" ${{ github.event.inputs.version }}
